# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate draws from a multivariate normal distribution
#'
#' @param n Number of samples.
#' @param mu Mean vector.
#' @param Sigma Covariance matrix.
#' @return Draws from the normal distribution.
#' @details This is essentially a stripped-down version of the mvrnorm function
#' from the MASS library in R. Through the magic of Rcpp we're transforming the
#' same standard normal draws as the R version. However, since Armadillo
#' follows a different convention from R in its definition of the
#' eign-decomposition, the output of this function will *not* be the same as
#' that of its R counterpart. Since we access R's function for generating
#' normal draws, we can set the seed from R.
#' @examples
#' mvrnorm(10, c(0,0), diag(1, 2, 2))
mvrnorm <- function(n, mu, Sigma) {
    .Call('fmscr_mvrnorm', PACKAGE = 'fmscr', n, mu, Sigma)
}

#' Calculate a sample quantile
#'
#' @param x Vector of data.
#' @param p Probability for desired quantile (e.g. 0.5 for median)
#' @return Sample quantile
#' @details There are many competing definitions of sample quantiles
#' (see Hyndman & Fan, 1996). Here we simply use the R default definition,
#' which corresponds to Definition 7 in Hyndman & Fan. See ?quantile in R for
#' more details.
#' @examples
#' foo <- rnorm(1000)
#' sample_quantile(foo, 0.16)
sample_quantile <- function(x, p) {
    .Call('fmscr_sample_quantile', PACKAGE = 'fmscr', x, p)
}

rcpp_hello <- function() {
    .Call('fmscr_rcpp_hello', PACKAGE = 'fmscr')
}

