# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate draws from a multivariate normal distribution
#'
#' @param n Number of samples.
#' @param mu Mean vector.
#' @param Sigma Covariance matrix.
#' @return Matrix of draws from the normal distribution: each row is a draw.
#' @details This is essentially a stripped-down version of the mvrnorm function
#' from the MASS library in R. Through the magic of Rcpp we're transforming the
#' same standard normal draws as the R version. However, since Armadillo
#' follows a different convention from R in its definition of the
#' eign-decomposition, the output of this function will *not* be the same as
#' that of its R counterpart. Since we access R's function for generating
#' normal draws, we can set the seed from R.
#' @examples
#' mvrnorm(10, c(0,0), diag(1, 2, 2))
mvrnorm <- function(n, mu, Sigma) {
    .Call('fmscr_mvrnorm', PACKAGE = 'fmscr', n, mu, Sigma)
}

#' Calculate a sample quantile
#'
#' @param x Vector of data.
#' @param p Probability for desired quantile (e.g. 0.5 for median)
#' @return Sample quantile
#' @details There are many competing definitions of sample quantiles
#' (see Hyndman & Fan, 1996). Here we simply use the R default definition,
#' which corresponds to Definition 7 in Hyndman & Fan. See ?quantile in R for
#' more details.
#' @examples
#' foo <- rnorm(1000)
#' sample_quantile(foo, 0.16)
sample_quantile <- function(x, p) {
    .Call('fmscr_sample_quantile', PACKAGE = 'fmscr', x, p)
}

#' Calculate (trimmed) mean-squared error.
#'
#' @param x Vector of estimates.
#' @param true True parameter value.
#' @param trim Fraction of estimates to discard (half from each tail) before
#' calculating MSE (defaults to zero)
#' @return (trimmed) mean-squared error
#' @examples
#' x <- rnorm(1000) + 0.5
#' MSE_trim(x, 0)
#' MSE_trim(x, 0, 0.1)
MSE_trim <- function(x, truth, trim = 0.0) {
    .Call('fmscr_MSE_trim', PACKAGE = 'fmscr', x, truth, trim)
}

#' Calculate median absolute deviation
#'
#' @param x Vector of estimates.
#' @param truth True value of the parameter.
#' @return Median absolute deviation.
#' @examples
#' x <- rnorm(1000) + 0.5
#' MAD(x, 0)
MAD <- function(x, truth) {
    .Call('fmscr_MAD', PACKAGE = 'fmscr', x, truth)
}

#' Calculate the empirical coverage probability of a matrix of confidence
#' intervals.
#'
#' @param conf_intervals Matrix of confidence intervals in which each row is a
#' CI, the first column is the lower confidence limit, and the second column is
#' the upper confidence limit.
#' @param truth True value of the parameter for which the CIs were constructed.
#' @return Empirical coverage probability.
#' @examples
#' xbar <- replicate(1000, mean(rnorm(25)))
#' ME <- qnorm(0.975) / 5
#' CIs <- cbind(xbar - ME, xbar + ME)
#' coverage_prob(CIs, 0)
coverage_prob <- function(conf_intervals, truth) {
    .Call('fmscr_coverage_prob', PACKAGE = 'fmscr', conf_intervals, truth)
}

#' Calculate empirical median width of a matrix of confidence intervals.
#'
#' @param conf_intervals Matrix of confidence intervals in which each row is a
#' CI, the first column is the lower confidence limit, and the second column is
#' the upper confidence limit.
#' @return Empirical median width of the confidence intervals.
#' @examples
#' xbar <- replicate(1000, mean(rnorm(25)))
#' ME <- qnorm(0.975) / 5
#' CIs <- cbind(xbar - ME, xbar + ME)
#' median_width(CIs)
median_width <- function(conf_intervals) {
    .Call('fmscr_median_width', PACKAGE = 'fmscr', conf_intervals)
}

rcpp_hello <- function() {
    .Call('fmscr_rcpp_hello', PACKAGE = 'fmscr')
}

